version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: crm_db  # Name of the database
      MYSQL_USER: crm_user  # Database user
      MYSQL_PASSWORD: crm_password  # Password for the user
      MYSQL_ROOT_PASSWORD: root_password  # Root user password
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "9090:9090"  # Expose Flask app port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Pass OpenAI API key
      - DB_HOST=db  # Hostname for the MySQL service
      - DB_PORT=3306  # MySQL default port
      - DB_NAME=crm_db  # Database name
      - DB_USER=crm_user  # Database user
      - DB_PASSWORD=crm_password  # Password for the user
    depends_on:
      - db  # Ensure the database starts before the Flask app
    volumes:
      - .:/app  # Mount the project directory for development
      - ./html:/app/html  # Explicitly mount the html folde

volumes:
  mysql_data:
